/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: ../sanity.schema.json
export type RichTextBlock = {
  _type: 'richTextBlock'
  eyebrow?: string
  heading?: string
  intro?: string
  content?: BlockContent
}

export type CallToActionBlock = {
  _type: 'callToActionBlock'
  eyebrow?: string
  heading?: string
  intro?: string
  theme?: 'surface' | 'secondary' | 'dark'
  image?: AccessibleImage
  cta?: Button
}

export type PostReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'post'
}

export type PostListBlock = {
  _type: 'postListBlock'
  eyebrow?: string
  heading?: string
  intro?: string
  selectionMode: 'latest' | 'manual'
  posts?: Array<
    {
      _key: string
    } & PostReference
  >
  limit: number
  layout: 'editorialGrid' | 'compactList'
}

export type ProductReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'product'
}

export type ProductsBlock = {
  _type: 'productsBlock'
  eyebrow?: string
  heading?: string
  intro?: string
  products: Array<
    {
      _key: string
    } & ProductReference
  >
}

export type TimelineBlock = {
  _type: 'timelineBlock'
  eyebrow?: string
  heading?: string
  intro?: string
  milestones: Array<{
    dateLabel: string
    title: string
    body?: string
    image: AccessibleImage
    _type: 'milestone'
    _key: string
  }>
}

export type SplitStoryBlock = {
  _type: 'splitStoryBlock'
  eyebrow?: string
  heading?: string
  intro?: string
  theme?: 'surface' | 'secondary'
  primaryImage?: AccessibleImage
  secondaryImage?: AccessibleImage
  cta?: Button
}

export type LocationReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'location'
}

export type AvailabilityBlock = {
  _type: 'availabilityBlock'
  eyebrow?: string
  heading?: string
  intro?: string
  image?: AccessibleImage
  location?: LocationReference
  percent: number
  lowLabel?: string
  highLabel?: string
  cta?: Button
}

export type FeatureGridBlock = {
  _type: 'featureGridBlock'
  eyebrow?: string
  heading?: string
  intro?: string
  variant?: 'cards' | 'compactAmenities'
  features: Array<{
    icon?: 'square' | 'users' | 'sun' | 'snowflake' | 'wifi' | 'cookie' | 'plug' | 'sparkles'
    title: string
    description?: string
    _type: 'feature'
    _key: string
  }>
}

export type MediaFeatureBlock = {
  _type: 'mediaFeatureBlock'
  eyebrow?: string
  heading?: string
  intro?: string
  image: AccessibleImage
  badge?: string
}

export type EventReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'event'
}

export type EventsBlock = {
  _type: 'eventsBlock'
  eyebrow?: string
  heading?: string
  intro?: string
  selectionMode?: 'manual' | 'upcoming'
  events?: Array<
    {
      _key: string
    } & EventReference
  >
  limit?: number
  cta?: Button
}

export type LocationsBlock = {
  _type: 'locationsBlock'
  eyebrow?: string
  heading?: string
  intro?: string
  variant?: 'cards' | 'alternatingDetails'
  locations: Array<
    {
      _key: string
    } & LocationReference
  >
  cta?: Button
}

export type MenuCategoryReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'menuCategory'
}

export type MenuCatalogBlock = {
  _type: 'menuCatalogBlock'
  eyebrow?: string
  heading?: string
  intro?: string
  categories: Array<
    {
      _key: string
    } & MenuCategoryReference
  >
}

export type MenuItemReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'menuItem'
}

export type MenuHighlightsBlock = {
  _type: 'menuHighlightsBlock'
  eyebrow?: string
  heading?: string
  intro?: string
  items: Array<
    {
      _key: string
    } & MenuItemReference
  >
  cta?: Button
}

export type AnnouncementTickerBlock = {
  _type: 'announcementTickerBlock'
  items: Array<{
    text: string
    link?: Link
    _type: 'announcement'
    _key: string
  }>
}

export type HeroBlock = {
  _type: 'heroBlock'
  variant: 'standard' | 'immersive'
  eyebrow?: string
  heading: string
  accentHeading?: string
  description?: string
  image?: AccessibleImage
  badge?: string
  primaryCta?: Button
  secondaryCta?: Button
}

export type PageBuilder = Array<
  | ({
      _key: string
    } & HeroBlock)
  | ({
      _key: string
    } & AnnouncementTickerBlock)
  | ({
      _key: string
    } & MenuHighlightsBlock)
  | ({
      _key: string
    } & MenuCatalogBlock)
  | ({
      _key: string
    } & LocationsBlock)
  | ({
      _key: string
    } & EventsBlock)
  | ({
      _key: string
    } & MediaFeatureBlock)
  | ({
      _key: string
    } & FeatureGridBlock)
  | ({
      _key: string
    } & AvailabilityBlock)
  | ({
      _key: string
    } & SplitStoryBlock)
  | ({
      _key: string
    } & TimelineBlock)
  | ({
      _key: string
    } & ProductsBlock)
  | ({
      _key: string
    } & PostListBlock)
  | ({
      _key: string
    } & CallToActionBlock)
  | ({
      _key: string
    } & RichTextBlock)
  | ({
      _key: string
    } & CallToAction)
  | ({
      _key: string
    } & InfoSection)
>

export type Seo = {
  _type: 'seo'
  metaTitle?: string
  metaDescription?: string
  openGraphImage?: AccessibleImage
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type AccessibleImage = {
  _type: 'accessibleImage'
  asset?: SanityImageAssetReference
  media?: unknown
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  alt: string
}

export type PageReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'page'
}

export type Link = {
  _type: 'link'
  linkType?: 'href' | 'page' | 'post'
  href?: string
  page?: PageReference
  post?: PostReference
  openInNewTab?: boolean
}

export type CallToAction = {
  _type: 'callToAction'
  eyebrow?: string
  heading: string
  body?: BlockContentTextOnly
  button?: Button
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  theme?: 'light' | 'dark'
  contentAlignment?: 'textFirst' | 'imageFirst'
}

export type InfoSection = {
  _type: 'infoSection'
  heading?: string
  subheading?: string
  content?: BlockContent
}

export type BlockContentTextOnly = Array<{
  children?: Array<{
    marks?: Array<string>
    text?: string
    _type: 'span'
    _key: string
  }>
  style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
  listItem?: 'bullet' | 'number'
  markDefs?: Array<{
    href?: string
    _type: 'link'
    _key: string
  }>
  level?: number
  _type: 'block'
  _key: string
}>

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        linkType?: 'href' | 'page' | 'post'
        href?: string
        page?: PageReference
        post?: PostReference
        openInNewTab?: boolean
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }
  | {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
      _key: string
    }
>

export type Button = {
  _type: 'button'
  buttonText?: string
  link?: Link
}

export type Product = {
  _id: string
  _type: 'product'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  label?: string
  description?: string
  price?: number
  priceLabel?: string
  image: AccessibleImage
  ctaLabel?: string
  ctaLink?: Link
  migrationKey?: string
}

export type Event = {
  _id: string
  _type: 'event'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  category?: string
  dateLabel?: string
  startsAt?: string
  endsAt?: string
  description?: string
  image: AccessibleImage
  registrationLink?: Link
  migrationKey?: string
}

export type MenuItem = {
  _id: string
  _type: 'menuItem'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  category: MenuCategoryReference
  description?: string
  price?: number
  priceLabel?: string
  image?: AccessibleImage
  status?: 'available' | 'hidden'
  migrationKey?: string
}

export type MenuCategory = {
  _id: string
  _type: 'menuCategory'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  description?: string
  order?: number
  migrationKey?: string
}

export type Location = {
  _id: string
  _type: 'location'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  label?: string
  address: string
  shortDescription?: string
  description?: string
  hours?: string
  image: AccessibleImage
  bookingLink?: Link
  availabilityLabel?: string
  availabilityPercent?: number
  migrationKey?: string
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type BlogPage = {
  _id: string
  _type: 'blogPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  seo?: Seo
  pageBuilder: PageBuilder
}

export type HomePage = {
  _id: string
  _type: 'homePage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  seo?: Seo
  pageBuilder: PageBuilder
}

export type Settings = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<{
      linkType?: 'href' | 'page' | 'post'
      href?: string
      page?: PageReference
      post?: PostReference
      openInNewTab?: boolean
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    metadataBase?: string
    _type: 'image'
  }
  brandName?: string
  logoText?: string
  navigation?: Array<{
    label: string
    link: Link
    _type: 'navigationItem'
    _key: string
  }>
  headerStatus?: string
  headerCta?: Button
  footerIntro?: string
  footerGroups?: Array<{
    title: string
    links?: Array<{
      label: string
      link: Link
      _type: 'footerLink'
      _key: string
    }>
    _type: 'footerGroup'
    _key: string
  }>
  footerLocations?: Array<
    {
      _key: string
    } & LocationReference
  >
  contactEmail?: string
  copyright?: string
  defaultSeo?: Seo
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  seo?: Seo
  heading?: string
  subheading?: string
  pageBuilder: PageBuilder
  migrationKey?: string
}

export type PersonReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'person'
}

export type Post = {
  _id: string
  _type: 'post'
  _createdAt: string
  _updatedAt: string
  _rev: string
  migrationKey?: string
  title: string
  slug: Slug
  content?: BlockContent
  excerpt?: string
  coverImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  date?: string
  author?: PersonReference
}

export type Person = {
  _id: string
  _type: 'person'
  _createdAt: string
  _updatedAt: string
  _rev: string
  firstName: string
  lastName: string
  picture: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
}

export type SanityAssistInstructionTask = {
  _type: 'sanity.assist.instructionTask'
  path?: string
  instructionKey?: string
  started?: string
  updated?: string
  info?: string
}

export type SanityAssistTaskStatus = {
  _type: 'sanity.assist.task.status'
  tasks?: Array<
    {
      _key: string
    } & SanityAssistInstructionTask
  >
}

export type SanityAssistSchemaTypeAnnotations = {
  _type: 'sanity.assist.schemaType.annotations'
  title?: string
  fields?: Array<
    {
      _key: string
    } & SanityAssistSchemaTypeField
  >
}

export type SanityAssistOutputType = {
  _type: 'sanity.assist.output.type'
  type?: string
}

export type SanityAssistOutputField = {
  _type: 'sanity.assist.output.field'
  path?: string
}

export type AssistInstructionContextReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'assist.instruction.context'
}

export type SanityAssistInstructionContext = {
  _type: 'sanity.assist.instruction.context'
  reference: AssistInstructionContextReference
}

export type AssistInstructionContext = {
  _id: string
  _type: 'assist.instruction.context'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  context?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type SanityAssistInstructionUserInput = {
  _type: 'sanity.assist.instruction.userInput'
  message: string
  description?: string
}

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<
    | {
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }
    | ({
        _key: string
      } & SanityAssistInstructionFieldRef)
    | ({
        _key: string
      } & SanityAssistInstructionContext)
    | ({
        _key: string
      } & SanityAssistInstructionUserInput)
  >
  style?: 'normal'
  listItem?: never
  markDefs?: null
  level?: number
  _type: 'block'
  _key: string
}>

export type SanityAssistInstructionFieldRef = {
  _type: 'sanity.assist.instruction.fieldRef'
  path?: string
}

export type SanityAssistInstruction = {
  _type: 'sanity.assist.instruction'
  prompt?: SanityAssistInstructionPrompt
  icon?: string
  title?: string
  userId?: string
  createdById?: string
  output?: Array<
    | ({
        _key: string
      } & SanityAssistOutputField)
    | ({
        _key: string
      } & SanityAssistOutputType)
  >
}

export type SanityAssistSchemaTypeField = {
  _type: 'sanity.assist.schemaType.field'
  path?: string
  instructions?: Array<
    {
      _key: string
    } & SanityAssistInstruction
  >
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | RichTextBlock
  | CallToActionBlock
  | PostReference
  | PostListBlock
  | ProductReference
  | ProductsBlock
  | TimelineBlock
  | SplitStoryBlock
  | LocationReference
  | AvailabilityBlock
  | FeatureGridBlock
  | MediaFeatureBlock
  | EventReference
  | EventsBlock
  | LocationsBlock
  | MenuCategoryReference
  | MenuCatalogBlock
  | MenuItemReference
  | MenuHighlightsBlock
  | AnnouncementTickerBlock
  | HeroBlock
  | PageBuilder
  | Seo
  | SanityImageAssetReference
  | AccessibleImage
  | PageReference
  | Link
  | CallToAction
  | InfoSection
  | BlockContentTextOnly
  | BlockContent
  | Button
  | Product
  | Event
  | MenuItem
  | MenuCategory
  | Location
  | Slug
  | BlogPage
  | HomePage
  | Settings
  | SanityImageCrop
  | SanityImageHotspot
  | Page
  | PersonReference
  | Post
  | Person
  | SanityAssistInstructionTask
  | SanityAssistTaskStatus
  | SanityAssistSchemaTypeAnnotations
  | SanityAssistOutputType
  | SanityAssistOutputField
  | AssistInstructionContextReference
  | SanityAssistInstructionContext
  | AssistInstructionContext
  | SanityAssistInstructionUserInput
  | SanityAssistInstructionPrompt
  | SanityAssistInstructionFieldRef
  | SanityAssistInstruction
  | SanityAssistSchemaTypeField
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
